import type {
  MarketplaceAgent,
  OfficeAgent,
  Task,
  Meeting,
  Output,
  ChatMessage,
  EventLog,
} from '@/types';

// 辅助函数：生成唯一 ID
export function generateId(prefix: string): string {
  return `${prefix}_${Math.random().toString(36).substring(2, 9)}`;
}

// 人才市场 Agent 种子数据
export const marketplaceAgents: MarketplaceAgent[] = [
  {
    id: 'market_alice',
    name: 'Alice',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Alice&backgroundColor=b6e3f4',
    title: '数据分析师',
    platform: 'Hermes',
    skills: ['数据分析', '统计建模', 'SQL', '可视化', '机器学习'],
    tools: ['Python', 'Database', 'Excel', 'Web Search'],
    status: 'ONLINE',
    description: '严谨细致的数据分析专家，擅长从海量数据中发现有价值的洞察，以数据驱动决策。',
  },
  {
    id: 'market_bob',
    name: 'Bob',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Bob&backgroundColor=c0aede',
    title: '开发工程师',
    platform: 'Hermes',
    skills: ['Python开发', 'API设计', '后端架构', '数据库优化'],
    tools: ['Python', 'Shell', 'Database', 'SSH', 'Git'],
    status: 'BUSY',
    description: '全栈开发工程师，专注于高性能后端系统与 API 设计，代码风格简洁优雅。',
  },
  {
    id: 'market_eve',
    name: 'Eve',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Eve&backgroundColor=ffdfbf',
    title: '文案专家',
    platform: 'Hermes',
    skills: ['内容创作', '品牌文案', '用户研究', 'SEO优化'],
    tools: ['Web Search', 'Browser', 'Excel'],
    status: 'ONLINE',
    description: '富有创意的文案专家，擅长将复杂的产品概念转化为打动人心的文字。',
  },
  {
    id: 'market_hermes_assistant',
    name: 'Hermes-Assistant',
    avatar: 'https://api.dicebear.com/7.x/bottts/svg?seed=Hermes&backgroundColor=e5e7eb',
    title: '智能助手',
    platform: 'Hermes',
    skills: ['问答助手', '日程管理', '信息检索', '会议纪要'],
    tools: ['Web Search', 'Email', 'Browser', 'MCP'],
    status: 'ONLINE',
    description: '通用型智能助手，能够快速响应各类办公需求，协助整理信息与安排日程。',
  },
  {
    id: 'market_openclaw',
    name: 'OpenClaw-Agent',
    avatar: 'https://api.dicebear.com/7.x/bottts/svg?seed=OpenClaw&backgroundColor=bbf7d0',
    title: '爬虫专家',
    platform: 'OpenClaw',
    skills: ['网络爬虫', '数据采集', '竞品监控', '信息聚合'],
    tools: ['Browser', 'Shell', 'Database', 'Web Search'],
    status: 'ONLINE',
    description: '数据采集与爬虫专家，擅长从公开渠道获取结构化数据并持续监控竞品动态。',
  },
  {
    id: 'market_data_scientist',
    name: 'Data-Scientist',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=DataScientist&backgroundColor=ddd6fe',
    title: '数据科学家',
    platform: 'CrewAI',
    skills: ['机器学习', '预测建模', '数据可视化', 'A/B测试'],
    tools: ['Python', 'Database', 'Excel', 'Browser'],
    status: 'BUSY',
    description: '数据科学家，专注于机器学习模型构建与业务预测分析。',
  },
  {
    id: 'market_designer',
    name: 'Creative-Designer',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Designer&backgroundColor=fecaca',
    title: '设计师',
    platform: 'LangGraph',
    skills: ['UI设计', '视觉设计', '设计系统', '原型制作'],
    tools: ['Browser', 'Excel'],
    status: 'OFFLINE',
    description: '创意设计师，擅长现代感界面设计与用户体验优化。',
  },
  {
    id: 'market_finance',
    name: 'Finance-Pro',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Finance&backgroundColor=fde68a',
    title: '财务分析师',
    platform: 'CrewAI',
    skills: ['财务分析', '报表制作', '预算管理', '风险评估'],
    tools: ['Excel', 'Database', 'Web Search', 'Python'],
    status: 'ONLINE',
    description: '资深财务分析师，能够快速理解业务数据并生成专业财务报告。',
  },
];

// 已雇佣 Agent 种子数据
export const officeAgents: OfficeAgent[] = [
  {
    id: 'office_alice',
    marketplaceId: 'market_alice',
    name: 'Alice',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Alice&backgroundColor=b6e3f4',
    title: '数据分析师',
    platform: 'Hermes',
    platformAgentId: 'hermes_agent_001',
    status: 'ONLINE',
    hiredAt: '2024-01-15T09:00:00',
    lastActiveAt: '2026-06-23T11:30:00',
    department: '数据分析部',
    managerId: 'ceo',
    soul: {
      identity: '严谨细致的数据分析专家',
      goal: '从海量数据中发现有价值的洞察，以数据驱动决策',
      principles: '数据说话、逻辑先行、结论可验证',
      style: '冷静、理性、条理清晰',
      description: 'Alice 擅长将复杂的数据转化为清晰的商业洞察，习惯用图表和数字支撑每一个结论。',
    },
    skills: ['数据分析', '统计建模', 'SQL', '可视化', '机器学习'],
    tools: ['Python', 'Database', 'Excel', 'Web Search'],
    memory: [
      '负责新能源行业研究',
      '负责用户增长数据分析',
      '熟悉公司产品核心指标体系',
    ],
    performance: {
      totalTasks: 128,
      successTasks: 118,
      failedTasks: 10,
      meetingCount: 24,
    },
  },
  {
    id: 'office_bob',
    marketplaceId: 'market_bob',
    name: 'Bob',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Bob&backgroundColor=c0aede',
    title: '开发工程师',
    platform: 'Hermes',
    platformAgentId: 'hermes_agent_002',
    status: 'WORKING',
    hiredAt: '2024-02-01T10:00:00',
    lastActiveAt: '2026-06-23T11:20:00',
    department: '技术研发部',
    managerId: 'ceo',
    soul: {
      identity: '全栈开发工程师',
      goal: '构建高性能、可维护的技术系统',
      principles: '代码即文档、简洁胜于复杂、测试先行',
      style: '务实、高效、注重细节',
      description: 'Bob 专注于后端系统与 API 设计，追求优雅的代码结构与稳定的系统性能。',
    },
    skills: ['Python开发', 'API设计', '后端架构', '数据库优化'],
    tools: ['Python', 'Shell', 'Database', 'SSH', 'Git'],
    memory: [
      '负责服务器运维',
      '负责核心 API 接口开发',
      '维护代码规范与最佳实践',
    ],
    performance: {
      totalTasks: 156,
      successTasks: 148,
      failedTasks: 8,
      meetingCount: 18,
    },
  },
  {
    id: 'office_eve',
    marketplaceId: 'market_eve',
    name: 'Eve',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Eve&backgroundColor=ffdfbf',
    title: '文案专家',
    platform: 'Hermes',
    platformAgentId: 'hermes_agent_003',
    status: 'ONLINE',
    hiredAt: '2024-02-20T14:00:00',
    lastActiveAt: '2026-06-23T11:25:00',
    department: '市场运营部',
    managerId: 'ceo',
    soul: {
      identity: '富有创意的文案专家',
      goal: '用精准的文字传递产品价值',
      principles: '用户视角、简洁有力、情感共鸣',
      style: '活泼、细腻、善于表达',
      description: 'Eve 擅长将复杂的产品概念转化为打动人心的文字，关注用户真实需求。',
    },
    skills: ['内容创作', '品牌文案', '用户研究', 'SEO优化'],
    tools: ['Web Search', 'Browser', 'Excel'],
    memory: [
      '负责品牌官网文案',
      '负责产品发布内容策划',
      '维护用户画像与关键词库',
    ],
    performance: {
      totalTasks: 96,
      successTasks: 91,
      failedTasks: 5,
      meetingCount: 21,
    },
  },
  {
    id: 'office_hermes',
    marketplaceId: 'market_hermes_assistant',
    name: 'Hermes-Assistant',
    avatar: 'https://api.dicebear.com/7.x/bottts/svg?seed=Hermes&backgroundColor=e5e7eb',
    title: '智能助手',
    platform: 'Hermes',
    platformAgentId: 'hermes_agent_004',
    status: 'ONLINE',
    hiredAt: '2024-03-01T08:00:00',
    lastActiveAt: '2026-06-23T11:35:00',
    department: '综合支持部',
    managerId: 'ceo',
    soul: {
      identity: '通用型智能助手',
      goal: '提升办公效率，快速响应各类需求',
      principles: '准确、及时、简洁',
      style: '友好、专业、高效',
      description: 'Hermes-Assistant 是办公室的多面手，能够快速检索信息、整理会议纪要并协助日常事务。',
    },
    skills: ['问答助手', '日程管理', '信息检索', '会议纪要'],
    tools: ['Web Search', 'Email', 'Browser', 'MCP'],
    memory: [
      '负责会议安排与纪要整理',
      '负责常见问题的快速解答',
      '负责办公信息的聚合与推送',
    ],
    performance: {
      totalTasks: 210,
      successTasks: 202,
      failedTasks: 8,
      meetingCount: 45,
    },
  },
];

// 任务种子数据
export const tasks: Task[] = [
  {
    id: 'task_001',
    name: '市场数据分析报告',
    agentId: 'office_alice',
    agentName: 'Alice',
    status: 'Completed',
    startedAt: '2026-06-23T09:00:00',
    endedAt: '2026-06-23T10:30:00',
    duration: 90,
    outputId: 'output_001',
  },
  {
    id: 'task_002',
    name: '用户需求文档撰写',
    agentId: 'office_eve',
    agentName: 'Eve',
    status: 'Completed',
    startedAt: '2026-06-23T08:30:00',
    endedAt: '2026-06-23T09:45:00',
    duration: 75,
    outputId: 'output_002',
  },
  {
    id: 'task_003',
    name: 'API 接口开发',
    agentId: 'office_bob',
    agentName: 'Bob',
    status: 'Running',
    startedAt: '2026-06-23T11:20:00',
    outputId: 'output_003',
  },
  {
    id: 'task_004',
    name: '竞品爬取任务',
    agentId: 'office_openclaw',
    agentName: 'OpenClaw-Agent',
    status: 'Running',
    startedAt: '2026-06-23T11:15:00',
    outputId: 'output_004',
  },
  {
    id: 'task_005',
    name: '数据可视化图表',
    agentId: 'office_data_scientist',
    agentName: 'Data-Scientist',
    status: 'Completed',
    startedAt: '2026-06-23T07:50:00',
    endedAt: '2026-06-23T08:50:00',
    duration: 60,
    outputId: 'output_005',
  },
  {
    id: 'task_006',
    name: '服务器日志巡检',
    agentId: 'office_bob',
    agentName: 'Bob',
    status: 'Pending',
  },
];

// 会议种子数据
export const meetings: Meeting[] = [
  {
    id: 'meeting_001',
    topic: '产品规划讨论',
    agentIds: ['office_alice', 'office_bob', 'office_eve'],
    status: 'finished',
    createdAt: '2026-06-23T10:00:00',
    rounds: [
      {
        round: 1,
        name: '独立意见',
        messages: [
          { role: 'agent', agentId: 'office_alice', agentName: 'Alice', content: '从数据角度看，本季度用户增长趋势良好，但留存率仍有提升空间。', timestamp: '2026-06-23T10:05:00' },
          { role: 'agent', agentId: 'office_bob', agentName: 'Bob', content: '技术层面已准备好新功能的基础架构，可以支持下个月的迭代。', timestamp: '2026-06-23T10:06:00' },
          { role: 'agent', agentId: 'office_eve', agentName: 'Eve', content: '市场文案方面，我建议强调新功能带来的效率提升。', timestamp: '2026-06-23T10:07:00' },
        ],
      },
      {
        round: 2,
        name: '交叉评论',
        messages: [
          { role: 'agent', agentId: 'office_bob', agentName: 'Bob', content: '同意 Alice 对留存率的判断，新功能可以增加用户粘性。', timestamp: '2026-06-23T10:10:00' },
          { role: 'agent', agentId: 'office_eve', agentName: 'Eve', content: 'Bob 提到的架构支持很重要，我们可以围绕效率提升做内容。', timestamp: '2026-06-23T10:11:00' },
        ],
      },
      {
        round: 3,
        name: '达成共识',
        messages: [
          { role: 'agent', agentId: 'office_alice', agentName: 'Alice', content: '大家一致认为：下阶段重点提升留存率，并通过新功能传递效率价值。', timestamp: '2026-06-23T10:15:00' },
        ],
      },
      {
        round: 4,
        name: '形成结论',
        messages: [
          { role: 'agent', agentId: 'office_hermes', agentName: 'Hermes-Assistant', content: '会议结论已整理，详见会议纪要。', timestamp: '2026-06-23T10:20:00' },
        ],
      },
    ],
    summary: '本次会议围绕下阶段产品规划展开，确认了以提升用户留存率为核心目标，并通过新功能传递效率价值。',
    decisions: ['下阶段核心目标：提升用户留存率', '新功能方向：效率提升工具', '下月启动迭代开发'],
    actions: ['Alice 输出留存率分析报告', 'Bob 准备技术方案', 'Eve 起草产品价值文案'],
  },
];

// 成果种子数据
export const outputs: Output[] = [
  {
    id: 'output_001',
    name: '市场数据分析报告.md',
    type: 'markdown',
    source: 'task',
    content: '# 市场数据分析报告\n\n## 核心发现\n\n1. 本季度用户增长 23%，主要来自移动端。\n2. 次日留存率 45%，较上月提升 3 个百分点。\n3. 核心功能使用频次增加，说明产品价值得到认可。\n\n## 建议\n\n- 继续优化新用户引导流程\n- 针对高价值用户推出专属权益',
    createdAt: '2026-06-23T10:30:00',
  },
  {
    id: 'output_002',
    name: '用户需求文档.md',
    type: 'markdown',
    source: 'task',
    content: '# 用户需求文档\n\n## 目标用户\n\n中小企业管理者、产品经理、数据分析师。\n\n## 主要需求\n\n1. 一站式管理数字员工\n2. 快速组织 Agent 协作会议\n3. 沉淀并复用任务成果',
    createdAt: '2026-06-23T09:45:00',
  },
  {
    id: 'output_003',
    name: 'API 接口设计.md',
    type: 'markdown',
    source: 'task',
    content: '# API 接口设计\n\n## 认证\n\n使用 JWT Token 进行身份验证。\n\n## 端点\n\n- GET /api/agents\n- POST /api/tasks\n- GET /api/meetings/:id',
    createdAt: '2026-06-23T11:20:00',
  },
  {
    id: 'output_004',
    name: '竞品数据.xlsx',
    type: 'link',
    source: 'task',
    url: '#',
    createdAt: '2026-06-23T11:15:00',
  },
  {
    id: 'output_005',
    name: '数据可视化图表.png',
    type: 'image',
    source: 'task',
    url: 'https://placehold.co/600x400/3B82F6/FFFFFF?text=Data+Visualization',
    createdAt: '2026-06-23T08:50:00',
  },
  {
    id: 'output_006',
    name: '产品规划会议纪要.md',
    type: 'markdown',
    source: 'meeting',
    content: '# 产品规划会议纪要\n\n## 结论\n\n下阶段以提升用户留存率为核心目标，通过新功能传递效率价值。\n\n## 行动项\n\n- Alice：留存率分析报告\n- Bob：技术方案\n- Eve：产品价值文案',
    createdAt: '2026-06-23T10:20:00',
  },
  {
    id: 'output_007',
    name: '设计规范.html',
    type: 'html',
    source: 'upload',
    content: '<h1>设计规范</h1><p>主色：#3B82F6，辅助色：#F8FAFC，圆角：12px</p>',
    createdAt: '2026-06-22T16:00:00',
  },
  {
    id: 'output_008',
    name: '项目介绍.pdf',
    type: 'pdf',
    source: 'upload',
    url: '#',
    createdAt: '2026-06-21T10:00:00',
  },
];

// 聊天消息种子数据
export const chatMessages: ChatMessage[] = [
  { id: 'chat_001', agentId: 'office_alice', role: 'user', content: '请帮我分析一下上个月的用户增长数据趋势', timestamp: '2026-06-23T11:29:00' },
  {
    id: 'chat_002',
    agentId: 'office_alice',
    role: 'agent',
    content: '好的，我来帮您分析上个月的用户增长数据。我将从以下几个维度进行分析：\n\n1. 整体增长趋势\n2. 渠道来源分析\n3. 用户活跃度变化\n4. 关键指标对比分析\n\n请稍等，我正在生成分析报告...',
    timestamp: '2026-06-23T11:30:00',
  },
  { id: 'chat_003', agentId: 'office_bob', role: 'user', content: 'API 接口开发进度如何？', timestamp: '2026-06-23T11:15:00' },
  { id: 'chat_004', agentId: 'office_bob', role: 'agent', content: '目前已完成 65%，核心接口已联调通过，预计今日下午完成剩余部分。', timestamp: '2026-06-23T11:16:00' },
  { id: 'chat_005', agentId: 'office_eve', role: 'user', content: '帮我写一份产品发布的宣传文案', timestamp: '2026-06-23T10:30:00' },
  { id: 'chat_006', agentId: 'office_eve', role: 'agent', content: '没问题，我先了解一下产品核心卖点和目标受众，稍后给您初稿。', timestamp: '2026-06-23T10:31:00' },
];

// 事件日志种子数据
export const eventLogs: EventLog[] = [
  { id: 'event_001', type: 'agent', title: '与 Alice 开始对话', description: '11:30', timestamp: '2026-06-23T11:30:00' },
  { id: 'event_002', type: 'meeting', title: '创建会议室"产品规划讨论"', description: '11:20', timestamp: '2026-06-23T11:20:00' },
  { id: 'event_003', type: 'task', title: 'Bob 完成任务"登录模块开发"', description: '11:15', timestamp: '2026-06-23T11:15:00' },
  { id: 'event_004', type: 'agent', title: 'Eve 加入办公室', description: '11:10', timestamp: '2026-06-23T11:10:00' },
  { id: 'event_005', type: 'agent', title: 'Data-Scientist 更新了技能', description: '11:05', timestamp: '2026-06-23T11:05:00' },
  { id: 'event_006', type: 'task', title: 'Alice 开始任务"市场数据分析"', description: '09:00', timestamp: '2026-06-23T09:00:00' },
  { id: 'event_007', type: 'system', title: '系统状态检查完成', description: '全部服务正常', timestamp: '2026-06-23T08:00:00' },
  { id: 'event_008', type: 'agent', title: 'OpenClaw-Agent 被雇佣', description: '加入技术研发部', timestamp: '2026-06-22T16:00:00' },
];
